# Generated by Django 4.2.6 on 2023-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
