# Generated by Django 4.2.6 on 2023-10-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='studentid',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
