# Generated by Django 4.2.6 on 2023-10-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_subjectmarks_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectMarks',
        ),
    ]
